-- Lead Manager — Postgres schema
-- IDs are generated by the application (uuid package), not the database,
-- so no pgcrypto/uuid-ossp extension is required.

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin','sales_manager','sales_rep')),
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crm_integrations (
  id UUID PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('salesforce','hubspot')),
  connected_by UUID REFERENCES users(id),
  access_token_encrypted TEXT,
  refresh_token_encrypted TEXT,
  instance_url TEXT,
  sync_frequency TEXT DEFAULT 'hourly',
  last_synced_at TIMESTAMPTZ,
  status TEXT DEFAULT 'active' CHECK (status IN ('active','paused','error')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS field_mappings (
  id UUID PRIMARY KEY,
  integration_id UUID REFERENCES crm_integrations(id) ON DELETE CASCADE,
  external_field TEXT NOT NULL,
  internal_field TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lead_sources (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  mobile TEXT,
  company TEXT,
  job_title TEXT,
  website TEXT,
  street TEXT,
  city TEXT,
  state TEXT,
  country TEXT,
  postal_code TEXT,
  lead_source_id INT REFERENCES lead_sources(id),
  industry TEXT,
  owner_id UUID REFERENCES users(id),
  status TEXT DEFAULT 'new' CHECK (status IN ('new','contacted','qualified','unqualified','duplicate')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
  expected_deal_size NUMERIC,
  ai_score NUMERIC,
  external_id TEXT,
  duplicate_of UUID REFERENCES leads(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON leads(phone);
CREATE INDEX IF NOT EXISTS idx_leads_company_name ON leads(company, first_name, last_name);
CREATE INDEX IF NOT EXISTS idx_leads_owner ON leads(owner_id);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);

CREATE TABLE IF NOT EXISTS lead_notes (
  id UUID PRIMARY KEY,
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
  author_id UUID REFERENCES users(id),
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lead_activities (
  id UUID PRIMARY KEY,
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES users(id),
  action TEXT NOT NULL,
  detail TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lead_assignments (
  id UUID PRIMARY KEY,
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
  assigned_to UUID REFERENCES users(id),
  assigned_by UUID REFERENCES users(id),
  assigned_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tags (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS lead_tags (
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
  tag_id INT REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (lead_id, tag_id)
);

CREATE TABLE IF NOT EXISTS import_jobs (
  id UUID PRIMARY KEY,
  source TEXT NOT NULL,
  file_name TEXT,
  imported_by UUID REFERENCES users(id),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed')),
  total_rows INT DEFAULT 0,
  success_count INT DEFAULT 0,
  failed_count INT DEFAULT 0,
  duplicate_count INT DEFAULT 0,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_errors (
  id UUID PRIMARY KEY,
  import_job_id UUID REFERENCES import_jobs(id) ON DELETE CASCADE,
  row_number INT,
  reason TEXT,
  raw_row JSONB
);

CREATE TABLE IF NOT EXISTS duplicate_rules (
  id UUID PRIMARY KEY,
  match_fields TEXT NOT NULL,
  action TEXT DEFAULT 'flag' CHECK (action IN ('flag','merge','ignore','block')),
  priority INT DEFAULT 0
);

CREATE OR REPLACE VIEW v_lead_dashboard AS
SELECT
  l.id, l.first_name, l.last_name, l.email, l.phone, l.company, l.job_title,
  ls.name AS source, l.status, l.priority, u.name AS owner_name,
  l.created_at, l.updated_at, l.ai_score
FROM leads l
LEFT JOIN lead_sources ls ON l.lead_source_id = ls.id
LEFT JOIN users u ON l.owner_id = u.id;
